project:
  type: website

website:
  title: "quarto"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Life1zALier
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto

